// TOEIC頻出1000語データベース
// 実際の実装では外部JSONファイルまたはAPIから読み込み

import { VocabularyWord, VocabularyLevel } from '@/types/vocabulary';

// カテゴリ定義
export const WORD_CATEGORIES = [
    'ビジネス・雇用',
    'オフィス・事務',
    'マーケティング・販売',
    '財務・会計',
    '製造・生産',
    '旅行・ホテル',
    'レストラン・飲食',
    '会議・イベント',
    '契約・法律',
    '技術・IT',
    'コミュニケーション',
    '一般ビジネス',
] as const;

// Level 1: 基礎 (~600点) - 100語以上
const level1Base = [
    { word: 'apply', meaning: '応募する、申し込む', category: 'ビジネス・雇用' },
    { word: 'available', meaning: '利用可能な', category: '一般ビジネス' },
    { word: 'confirm', meaning: '確認する', category: 'コミュニケーション' },
    { word: 'schedule', meaning: '予定、スケジュール', category: 'オフィス・事務' },
    { word: 'meeting', meaning: '会議', category: '会議・イベント' },
    { word: 'customer', meaning: '顧客', category: 'マーケティング・販売' },
    { word: 'product', meaning: '製品', category: '製造・生産' },
    { word: 'service', meaning: 'サービス', category: '一般ビジネス' },
    { word: 'report', meaning: '報告書', category: 'オフィス・事務' },
    { word: 'manager', meaning: '管理者', category: 'ビジネス・雇用' },
    { word: 'advertise', meaning: '宣伝する', category: 'マーケティング・販売' },
    { word: 'agreement', meaning: '合意、契約', category: '契約・法律' },
    { word: 'appointment', meaning: '約束、予約', category: '一般ビジネス' },
    { word: 'assist', meaning: '助ける、援助する', category: 'コミュニケーション' },
    { word: 'attendance', meaning: '出席、出席者数', category: '会議・イベント' },
    { word: 'benefit', meaning: '利益、手当', category: 'ビジネス・雇用' },
    { word: 'budget', meaning: '予算', category: '財務・会計' },
    { word: 'calendar', meaning: 'カレンダー、日程', category: 'オフィス・事務' },
    { word: 'campaign', meaning: 'キャンペーン、活動', category: 'マーケティング・販売' },
    { word: 'cancel', meaning: '取り消す、キャンセルする', category: '一般ビジネス' },
    { word: 'candidate', meaning: '候補者', category: 'ビジネス・雇用' },
    { word: 'career', meaning: 'キャリア、経歴', category: 'ビジネス・雇用' },
    { word: 'clerk', meaning: '事務員、店員', category: 'オフィス・事務' },
    { word: 'client', meaning: 'クライアント、顧客', category: '一般ビジネス' },
    { word: 'colleague', meaning: '同僚', category: 'ビジネス・雇用' },
    { word: 'committee', meaning: '委員会', category: '会議・イベント' },
    { word: 'comparison', meaning: '比較', category: '一般ビジネス' },
    { word: 'compensation', meaning: '補償、報酬', category: 'ビジネス・雇用' },
    { word: 'complaint', meaning: '苦情、クレーム', category: 'コミュニケーション' },
    { word: 'conclude', meaning: '結論づける、終える', category: '会議・イベント' },
    { word: 'conference', meaning: '会議、協議会', category: '会議・イベント' },
    { word: 'contract', meaning: '契約', category: '契約・法律' },
    { word: 'contribution', meaning: '貢献、寄付', category: '一般ビジネス' },
    { word: 'convenient', meaning: '便利な', category: '一般ビジネス' },
    { word: 'cooperate', meaning: '協力する', category: 'コミュニケーション' },
    { word: 'correct', meaning: '正しい、訂正する', category: '一般ビジネス' },
    { word: 'cost', meaning: '費用', category: '財務・会計' },
    { word: 'deadline', meaning: '締め切り', category: 'オフィス・事務' },
    { word: 'decision', meaning: '決定、決断', category: '一般ビジネス' },
    { word: 'delivery', meaning: '配達、配送', category: '製造・生産' },
    { word: 'department', meaning: '部署、部門', category: 'ビジネス・雇用' },
    { word: 'description', meaning: '説明、記述', category: '一般ビジネス' },
    { word: 'development', meaning: '開発、発展', category: '技術・IT' },
    { word: 'discount', meaning: '割引', category: 'マーケティング・販売' },
    { word: 'document', meaning: '書類、文書', category: 'オフィス・事務' },
    { word: 'due', meaning: '期日の、到着予定の', category: '一般ビジネス' },
    { word: 'efficient', meaning: '効率的な', category: '一般ビジネス' },
    { word: 'employee', meaning: '従業員', category: 'ビジネス・雇用' },
    { word: 'equipment', meaning: '備品、装置', category: 'オフィス・事務' },
    { word: 'error', meaning: '間違い、エラー', category: '技術・IT' },
    { word: 'estimate', meaning: '見積もり、推定', category: '財務・会計' },
    { word: 'evaluation', meaning: '評価', category: 'ビジネス・雇用' },
    { word: 'expansion', meaning: '拡大、拡張', category: '一般ビジネス' },
    { word: 'experience', meaning: '経験', category: 'ビジネス・雇用' },
    { word: 'expert', meaning: '専門家', category: '技術・IT' },
    { word: 'extension', meaning: '延長、内線番号', category: 'コミュニケーション' },
    { word: 'facility', meaning: '施設、設備', category: '一般ビジネス' },
    { word: 'feedback', meaning: 'フィードバック、意見', category: 'コミュニケーション' },
    { word: 'file', meaning: 'ファイル、整理する', category: 'オフィス・事務' },
    { word: 'form', meaning: '書類、形式', category: '一般ビジネス' },
    { word: 'function', meaning: '機能、行事', category: '一般ビジネス' },
    { word: 'goal', meaning: '目標', category: '一般ビジネス' },
    { word: 'guarantee', meaning: '保証', category: '契約・法律' },
    { word: 'guideline', meaning: 'ガイドライン、指針', category: '一般ビジネス' },
    { word: 'hire', meaning: '雇う', category: 'ビジネス・雇用' },
    { word: 'improve', meaning: '改善する', category: '一般ビジネス' },
    { word: 'increase', meaning: '増加、増やす', category: '財務・会計' },
    { word: 'industry', meaning: '産業、業界', category: '一般ビジネス' },
    { word: 'information', meaning: '情報', category: 'コミュニケーション' },
    { word: 'instruction', meaning: '指示、説明', category: 'コミュニケーション' },
    { word: 'insurance', meaning: '保険', category: '財務・会計' },
    { word: 'interview', meaning: '面接、インタビュー', category: 'ビジネス・雇用' },
    { word: 'inventory', meaning: '在庫', category: '製造・生産' },
    { word: 'investment', meaning: '投資', category: '財務・会計' },
    { word: 'invoice', meaning: '請求書', category: '財務・会計' },
    { word: 'item', meaning: '品目、項目', category: '一般ビジネス' },
    { word: 'job', meaning: '仕事', category: 'ビジネス・雇用' },
    { word: 'launch', meaning: '開始する、発売する', category: 'マーケティング・販売' },
    { word: 'lease', meaning: '賃貸借', category: '契約・法律' },
    { word: 'list', meaning: '一覧、リスト', category: '一般ビジネス' },
    { word: 'loan', meaning: '融資、ローン', category: '財務・会計' },
    { word: 'location', meaning: '場所、立地', category: '一般ビジネス' },
    { word: 'maintenance', meaning: '整備、保守', category: '製造・生産' },
    { word: 'management', meaning: '経営、管理', category: '一般ビジネス' },
    { word: 'market', meaning: '市場', category: 'マーケティング・販売' },
    { word: 'message', meaning: 'メッセージ、伝言', category: 'コミュニケーション' },
    { word: 'offer', meaning: '申し出、オファー', category: '一般ビジネス' },
    { word: 'operation', meaning: '操業、運用', category: '製造・生産' },
    { word: 'order', meaning: '注文', category: '一般ビジネス' },
    { word: 'package', meaning: '小包、パッケージ', category: '製造・生産' },
    { word: 'payment', meaning: '支払い', category: '財務・会計' },
    { word: 'policy', meaning: '方針、規定', category: '一般ビジネス' },
    { word: 'prepare', meaning: '準備する', category: '一般ビジネス' },
    { word: 'presentation', meaning: 'プレゼンテーション', category: '会議・イベント' },
    { word: 'price', meaning: '価格', category: '財務・会計' },
    { word: 'procedure', meaning: '手順、手続き', category: '一般ビジネス' },
    { word: 'profit', meaning: '利益', category: '財務・会計' },
    { word: 'project', meaning: 'プロジェクト、計画', category: '一般ビジネス' },
    { word: 'promotion', meaning: '昇進、宣伝', category: 'ビジネス・雇用' },
    { word: 'proposal', meaning: '提案', category: '会議・イベント' },
    { word: 'quality', meaning: '品質', category: '製造・生産' },
    { word: 'receipt', meaning: '領収書、受け取り', category: '財務・会計' },
    { word: 'reference', meaning: '参照、推薦', category: '一般ビジネス' },
    { word: 'refund', meaning: '払い戻し、返金', category: '財務・会計' },
    { word: 'registration', meaning: '登録', category: '一般ビジネス' },
    { word: 'request', meaning: '要請、依頼', category: 'コミュニケーション' },
    { word: 'reservation', meaning: '予約', category: '一般ビジネス' },
    { word: 'resource', meaning: '資源、資産', category: '一般ビジネス' },
    { word: 'response', meaning: '返答、回答', category: 'コミュニケーション' },
];

// Level 2: 中級 (~750点) - 100語以上
const level2Base = [
    { word: 'notwithstanding', meaning: '～にもかかわらず', category: '一般ビジネス' },
    { word: 'substantial', meaning: '相当な、かなりの', category: '一般ビジネス' },
    { word: 'implement', meaning: '実施する、実装する', category: 'ビジネス・雇用' },
    { word: 'accommodate', meaning: '収容する、対応する', category: '旅行・ホテル' },
    { word: 'revenue', meaning: '収益', category: '財務・会計' },
    { word: 'competent', meaning: '有能な', category: 'ビジネス・雇用' },
    { word: 'liability', meaning: '責任、負債', category: '契約・法律' },
    { word: 'prospective', meaning: '見込みのある', category: 'マーケティング・販売' },
    { word: 'collaborate', meaning: '協力する', category: 'コミュニケーション' },
    { word: 'specifications', meaning: '仕様、明細', category: '技術・IT' },
    { word: 'accomplish', meaning: '達成する', category: '一般ビジネス' },
    { word: 'accumulate', meaning: '蓄積する', category: '財務・会計' },
    { word: 'acknowledge', meaning: '認める、受領を知らせる', category: 'コミュニケーション' },
    { word: 'acquisition', meaning: '買収、獲得', category: '一般ビジネス' },
    { word: 'adjourn', meaning: '休会する、延期する', category: '会議・イベント' },
    { word: 'administrative', meaning: '管理上の', category: 'オフィス・事務' },
    { word: 'advocate', meaning: '提唱する、支持する', category: '一般ビジネス' },
    { word: 'aggregate', meaning: '集計、合計の', category: '財務・会計' },
    { word: 'alleviate', meaning: '軽減する', category: '一般ビジネス' },
    { word: 'allocation', meaning: '割り当て', category: '財務・会計' },
    { word: 'annex', meaning: '別館、付録', category: '一般ビジネス' },
    { word: 'anticipate', meaning: '予想する、期待する', category: '一般ビジネス' },
    { word: 'appraisal', meaning: '評価、査定', category: 'ビジネス・雇用' },
    { word: 'approximate', meaning: 'おおよその', category: '一般ビジネス' },
    { word: 'arbitrate', meaning: '仲裁する', category: '契約・法律' },
    { word: 'assemble', meaning: '組み立てる、集める', category: '製造・生産' },
    { word: 'asset', meaning: '資産、強み', category: '財務・会計' },
    { word: 'attain', meaning: '達成する', category: '一般ビジネス' },
    { word: 'audit', meaning: '会計監査', category: '財務・会計' },
    { word: 'authorize', meaning: '権限を与える', category: '一般ビジネス' },
    { word: 'benchmark', meaning: '基準、比較対象', category: '一般ビジネス' },
    { word: 'beverage', meaning: '飲料', category: 'レストラン・飲食' },
    { word: 'bid', meaning: '入札', category: '契約・法律' },
    { word: 'breach', meaning: '契約違反、侵害', category: '契約・法律' },
    { word: 'broker', meaning: '仲介業者', category: '財務・会計' },
    { word: 'bulk', meaning: '大量、大半', category: '製造・生産' },
    { word: 'capability', meaning: '能力、可能性', category: '一般ビジネス' },
    { word: 'capital', meaning: '資本、首都', category: '財務・会計' },
    { word: 'catering', meaning: '仕出し、ケータリング', category: 'レストラン・飲食' },
    { word: 'certificate', meaning: '証明書', category: '一般ビジネス' },
    { word: 'chronological', meaning: '年代順の', category: '一般ビジネス' },
    { word: 'circulate', meaning: '循環させる、配布する', category: 'コミュニケーション' },
    { word: 'citation', meaning: '引用、表彰', category: '一般ビジネス' },
    { word: 'classification', meaning: '分類', category: '一般ビジネス' },
    { word: 'clause', meaning: '条項', category: '契約・法律' },
    { word: 'closure', meaning: '閉鎖、終結', category: '一般ビジネス' },
    { word: 'coincidence', meaning: '偶然の一致', category: '一般ビジネス' },
    { word: 'collateral', meaning: '担保', category: '財務・会計' },
    { word: 'commence', meaning: '開始する', category: '一般ビジネス' },
    { word: 'commodity', meaning: '商品、日用品', category: '一般ビジネス' },
    { word: 'compelling', meaning: '説得力のある', category: '一般ビジネス' },
    { word: 'compensate', meaning: '補償する', category: '一般ビジネス' },
    { word: 'compliance', meaning: '法令遵守、コンプライアンス', category: '契約・法律' },
    { word: 'comprehensive', meaning: '包括的な、総合的な', category: '一般ビジネス' },
    { word: 'compromise', meaning: '妥協する', category: '一般ビジネス' },
    { word: 'concession', meaning: '譲歩、利権', category: '契約・法律' },
    { word: 'condolence', meaning: '哀悼の意', category: 'コミュニケーション' },
    { word: 'confidential', meaning: '機密の', category: '一般ビジネス' },
    { word: 'consensus', meaning: '合意、コンセンサス', category: 'コミュニケーション' },
    { word: 'consistent', meaning: '一貫した', category: '一般ビジネス' },
    { word: 'consolidation', meaning: '合併、強化', category: '一般ビジネス' },
    { word: 'constitute', meaning: '構成する、～とみなされる', category: '一般ビジネス' },
    { word: 'consultant', meaning: 'コンサルタント', category: '一般ビジネス' },
    { word: 'containment', meaning: '抑制、封じ込め', category: '一般ビジネス' },
    { word: 'convene', meaning: '召集する', category: '会議・イベント' },
    { word: 'convey', meaning: '伝える、運ぶ', category: 'コミュニケーション' },
    { word: 'coordinator', meaning: 'コーディネーター', category: '一般ビジネス' },
    { word: 'corporate', meaning: '企業の', category: '一般ビジネス' },
    { word: 'correspondence', meaning: '通信、通信文', category: 'コミュニケーション' },
    { word: 'cost-effective', meaning: '費用対効果の高い', category: '財務・会計' },
    { word: 'courier', meaning: '宅配業者、クーリエ', category: '製造・生産' },
    { word: 'credential', meaning: '資格、実績', category: '一般ビジネス' },
    { word: 'cumulative', meaning: '累積的な', category: '一般ビジネス' },
    { word: 'curriculum', meaning: '教育課程、カリキュラム', category: '一般ビジネス' },
    { word: 'curtail', meaning: '削減する、短縮する', category: '一般ビジネス' },
    { word: 'custody', meaning: '保護、保管', category: '一般ビジネス' },
    { word: 'customized', meaning: '特注の、カスタマイズされた', category: '製造・生産' },
    { word: 'database', meaning: 'データベース', category: '技術・IT' },
    { word: 'debit', meaning: '借方、引き落とし', category: '財務・会計' },
    { word: 'delegate', meaning: '委任する、代表者', category: '一般ビジネス' },
    { word: 'demographic', meaning: '人口動態の', category: 'マーケティング・販売' },
    { word: 'density', meaning: '密度', category: '一般ビジネス' },
    { word: 'depreciation', meaning: '減価償却、価値の下落', category: '財務・会計' },
    { word: 'designated', meaning: '指定された', category: '一般ビジネス' },
    { word: 'deteriorate', meaning: '悪化する', category: '一般ビジネス' },
    { word: 'dimension', meaning: '寸法、次元', category: '一般ビジネス' },
    { word: 'disbursement', meaning: '支払い、支出', category: '財務・会計' },
    { word: 'discretion', meaning: '裁量、慎重さ', category: '一般ビジネス' },
    { word: 'discrepancy', meaning: '不一致、相違', category: '財務・会計' },
    { word: 'diversify', meaning: '多様化する', category: '一般ビジネス' },
    { word: 'dividend', meaning: '配当', category: '財務・会計' },
    { word: 'downsize', meaning: '規模を縮小する', category: '一般ビジネス' },
    { word: 'drastic', meaning: '抜本的な、過激な', category: '一般ビジネス' },
    { word: 'duplicate', meaning: '複製、複製の', category: '一般ビジネス' },
    { word: 'duration', meaning: '期間、持続', category: '一般ビジネス' },
    { word: 'earnings', meaning: '収益、所得', category: '財務・会計' },
    { word: 'economical', meaning: '経済的な', category: '一般ビジネス' },
    { word: 'edition', meaning: '（刊行物の）版', category: '一般ビジネス' },
    { word: 'educator', meaning: '教育者', category: '一般ビジネス' },
    { word: 'elaborate', meaning: '詳述する、精巧な', category: 'コミュニケーション' },
    { word: 'eligible', meaning: '資格がある', category: '一般ビジネス' },
    { word: 'eliminate', meaning: '取り除く', category: '一般ビジネス' },
    { word: 'emphasize', meaning: '強調する', category: 'コミュニケーション' },
    { word: 'endorse', meaning: '支持する、裏書きする', category: '一般ビジネス' },
];

// Level 3: 上級 (800+点) - 100語以上
const level3Base = [
    { word: 'contingent', meaning: '条件付きの、不測の事態', category: '契約・法律' },
    { word: 'mitigate', meaning: '軽減する、和らげる', category: '一般ビジネス' },
    { word: 'stipulate', meaning: '規定する', category: '契約・法律' },
    { word: 'confer', meaning: '協議する、授与する', category: 'コミュニケーション' },
    { word: 'procurement', meaning: '調達', category: '製造・生産' },
    { word: 'commensurate', meaning: '釣り合った', category: '財務・会計' },
    { word: 'exacerbate', meaning: '悪化させる', category: '一般ビジネス' },
    { word: 'incumbent', meaning: '現職の、義務として', category: 'ビジネス・雇用' },
    { word: 'litigation', meaning: '訴訟', category: '契約・法律' },
    { word: 'reimbursement', meaning: '払い戻し', category: '財務・会計' },
    { word: 'abrogate', meaning: '破棄する、廃止する', category: '契約・法律' },
    { word: 'acquiesce', meaning: '黙認する、同意する', category: '一般ビジネス' },
    { word: 'advent', meaning: '到来、出現', category: '一般ビジネス' },
    { word: 'adversary', meaning: '敵、反対者', category: '一般ビジネス' },
    { word: 'aesthetic', meaning: '美的な', category: '一般ビジネス' },
    { word: 'affluence', meaning: '富、豊かさ', category: '財務・会計' },
    { word: 'ambiguous', meaning: '曖昧な', category: 'コミュニケーション' },
    { word: 'ameliorate', meaning: '改善する', category: '一般ビジネス' },
    { word: 'anomalous', meaning: '異例の', category: '一般ビジネス' },
    { word: 'arbitrary', meaning: '恣意的な', category: '一般ビジネス' },
    { word: 'ascertain', meaning: '確かめる、突き止める', category: '一般ビジネス' },
    { word: 'attrition', meaning: '（人員の）自然減', category: 'ビジネス・雇用' },
    { word: 'augment', meaning: '増やす、増強する', category: '一般ビジネス' },
    { word: 'austere', meaning: '厳しい、簡素な', category: '一般ビジネス' },
    { word: 'autonomous', meaning: '自治の、自主的な', category: '一般ビジネス' },
    { word: 'belligerent', meaning: '好戦的な', category: '一般ビジネス' },
    { word: 'benevolent', meaning: '慈悲深い', category: '一般ビジネス' },
    { word: 'bolster', meaning: '支持する、強化する', category: '一般ビジネス' },
    { word: 'cacophony', meaning: '不協和音', category: '一般ビジネス' },
    { word: 'capitulate', meaning: '降伏する', category: '一般ビジネス' },
    { word: 'capricious', meaning: '気まぐれな', category: '一般ビジネス' },
    { word: 'clandestine', meaning: '秘密の', category: '一般ビジネス' },
    { word: 'coerce', meaning: '強制する', category: '一般ビジネス' },
    { word: 'cognizant', meaning: '認識している', category: '一般ビジネス' },
    { word: 'coherent', meaning: '首尾一貫した', category: 'コミュニケーション' },
    { word: 'complaisant', meaning: '丁寧な、従順な', category: '一般ビジネス' },
    { word: 'complicit', meaning: '共謀した', category: '一般ビジネス' },
    { word: 'conciliatory', meaning: '宥和的な', category: '一般ビジネス' },
    { word: 'conspicuous', meaning: '顕著な', category: '一般ビジネス' },
    { word: 'contentious', meaning: '論争を招く', category: 'コミュニケーション' },
    { word: 'conundrum', meaning: '難問', category: '一般ビジネス' },
    { word: 'converge', meaning: '収束する', category: '一般ビジネス' },
    { word: 'convivial', meaning: '陽気な、懇親の', category: 'レストラン・飲食' },
    { word: 'copious', meaning: '膨大な', category: '一般ビジネス' },
    { word: 'corroborate', meaning: '裏付ける', category: '契約・法律' },
    { word: 'cryptic', meaning: '謎めいた', category: '一般ビジネス' },
    { word: 'culpable', meaning: '非難に値する', category: '契約・法律' },
    { word: 'cursory', meaning: '雑な、せっかちな', category: '一般ビジネス' },
    { word: 'daunting', meaning: 'ひるませるような', category: '一般ビジネス' },
    { word: 'dearth', meaning: '不足', category: '一般ビジネス' },
    { word: 'decorum', meaning: '礼儀正しさ', category: 'ビジネス・雇用' },
    { word: 'deferential', meaning: '敬意を払う', category: 'ビジネス・雇用' },
    { word: 'deleterious', meaning: '有害な', category: '一般ビジネス' },
    { word: 'demagogue', meaning: '扇動者', category: '一般ビジネス' },
    { word: 'denigrate', meaning: '誹謗する', category: 'コミュニケーション' },
    { word: 'derivative', meaning: '派生的な', category: '一般ビジネス' },
    { word: 'desiccated', meaning: '乾燥した', category: '一般ビジネス' },
    { word: 'despot', meaning: '独裁者', category: '一般ビジネス' },
    { word: 'diaphanous', meaning: '透き通った', category: '一般ビジネス' },
    { word: 'didactic', meaning: '教訓的な', category: '一般ビジネス' },
    { word: 'disparate', meaning: '異種の', category: '一般ビジネス' },
    { word: 'dispel', meaning: '（疑いなどを）一掃する', category: '一般ビジネス' },
    { word: 'disrepute', meaning: '不評', category: '一般ビジネス' },
    { word: 'dogmatic', meaning: '独断的な', category: '一般ビジネス' },
    { word: 'ebullient', meaning: '溢れんばかりの情熱', category: '一般ビジネス' },
    { word: 'eclectic', meaning: '折衷的な、多才な', category: '一般ビジネス' },
    { word: 'edict', meaning: '布告、命令', category: '契約・法律' },
    { word: 'efface', meaning: '消し去る', category: '一般ビジネス' },
    { word: 'effervescent', meaning: '活気のある', category: '一般ビジネス' },
    { word: 'efficacious', meaning: '効果のある', category: '一般ビジネス' },
    { word: 'effrontery', meaning: '厚かましさ', category: '一般ビジネス' },
    { word: 'egregious', meaning: 'ひどく悪い', category: '一般ビジネス' },
    { word: 'elicit', meaning: '引き出す', category: 'コミュニケーション' },
    { word: 'eloquent', meaning: '雄弁な', category: 'コミュニケーション' },
    { word: 'elucidate', meaning: '解明する', category: 'コミュニケーション' },
    { word: 'emancipate', meaning: '解放する', category: '一般ビジネス' },
    { word: 'embellish', meaning: '飾る、装飾する', category: '一般ビジネス' },
    { word: 'eminent', meaning: '著名な', category: '一般ビジネス' },
    { word: 'emulate', meaning: '見習う', category: '一般ビジネス' },
    { word: 'enervate', meaning: '気力を奪う', category: '一般ビジネス' },
    { word: 'engender', meaning: '発生させる', category: '一般ビジネス' },
    { word: 'enigma', meaning: '謎', category: '一般ビジネス' },
    { word: 'entail', meaning: '伴う、必要とする', category: '一般ビジネス' },
    { word: 'ephemeral', meaning: '儚い、一時的な', category: '一般ビジネス' },
    { word: 'equanimity', meaning: '落ち着き', category: '一般ビジネス' },
    { word: 'equivocal', meaning: '曖昧な', category: '一般ビジネス' },
    { word: 'erudite', meaning: '博学な', category: '一般ビジネス' },
    { word: 'eschew', meaning: '避ける', category: '一般ビジネス' },
    { word: 'esoteric', meaning: '難解な', category: '一般ビジネス' },
    { word: 'euphemism', meaning: '婉曲表現', category: 'コミュニケーション' },
    { word: 'evanescent', meaning: '消えやすい', category: '一般ビジネス' },
    { word: 'exasperate', meaning: '憤慨させる', category: '一般ビジネス' },
    { word: 'exculpate', meaning: '無実にする', category: '契約・法律' },
    { word: 'exemplary', meaning: '模範的な', category: '一般ビジネス' },
    { word: 'exhort', meaning: '勧告する', category: 'コミュニケーション' },
    { word: 'exigent', meaning: '緊急の', category: '一般ビジネス' },
    { word: 'exonerate', meaning: '無罪にする', category: '契約・法律' },
    { word: 'expedite', meaning: '捗らせる', category: '一般ビジネス' },
    { word: 'expiate', meaning: '償う', category: '一般ビジネス' },
    { word: 'expunge', meaning: '抹消する', category: '一般ビジネス' },
    { word: 'extol', meaning: '激賞する', category: 'コミュニケーション' },
    { word: 'extraneous', meaning: '無関係な', category: '一般ビジネス' },
    { word: 'extricate', meaning: '救い出す', category: '一般ビジネス' },
    { word: 'exult', meaning: '大喜びする', category: 'コミュニケーション' },
    { word: 'fabricate', meaning: 'でっち上げる、製作する', category: '製造・生産' },
    { word: 'facetious', meaning: 'おどけた', category: 'コミュニケーション' },
];

export function generate1000Words(): VocabularyWord[] {
    const words: VocabularyWord[] = [];
    let id = 1;

    // Level 1
    level1Base.forEach(base => {
        words.push(createWord(id++, base.word, base.meaning, 1, base.category));
    });

    // Level 2
    level2Base.forEach(base => {
        words.push(createWord(id++, base.word, base.meaning, 2, base.category));
    });

    // Level 3
    level3Base.forEach(base => {
        words.push(createWord(id++, base.word, base.meaning, 3, base.category));
    });

    return words;
}

function createWord(
    id: number,
    word: string,
    meaning: string,
    level: VocabularyLevel,
    category: string
): VocabularyWord {
    return {
        id: `vocab_${id.toString().padStart(4, '0')}`,
        word,
        pronunciation: '/placeholder/',
        audioUrl: '',
        meaning,
        synonyms: [],
        antonyms: [],
        collocations: [],
        exampleSentence: `Example sentence using ${word}.`,
        exampleTranslation: `${word}を使った例文の和訳。`,
        level,
        category,
    };
}

// レベル別に取得
export function getWordsByLevel(level: VocabularyLevel): VocabularyWord[] {
    const allWords = generate1000Words();
    return allWords.filter(w => w.level === level);
}

// カテゴリ別に取得
export function getWordsByCategory(category: string): VocabularyWord[] {
    const allWords = generate1000Words();
    return allWords.filter(w => w.category === category);
}

// すべての単語を取得
export function getAllWords(): VocabularyWord[] {
    return generate1000Words();
}

// IDで単語を取得
export function getWordById(id: string): VocabularyWord | undefined {
    const allWords = generate1000Words();
    return allWords.find(w => w.id === id);
}
